### PR TITLE
read data and send to mqtt

### PR DESCRIPTION
**Pull request by Chibald**

### CODE REVIEW

**Comment by mvdklip** [comment]
@Chibald I see you closed the merge request already. This repo is for the Domoticz plugin. You script would be a better addition to https://github.com/aelias-eu/hewalex-geco-protocol. It already has a hewalex2mqtt.py script but if I understand correctly you made a PCWU version of that script. Maybe you can either create a combined version which supports both ZPS and PCWU or store it as a separate version?

**Comment by Chibald** [comment]
Hi, yes, I made a fork of your code and by accident made a PR into your
repo.
Maybe I should un-fork it to prevent this from happening in the future.

Nice work by the way, I'm now controlling my hewalex equipment through
OpenHab. It's great, thanks.

Op vr 12 nov. 2021 om 09:55 schreef Matthijs van der Klip <
***@***.***>:

**Comment by mvdklip** [comment]
Please note that I found an issue with register 304 for controlling the heatpump a few days ago. Somehow writing a 1 to it doesn't always enable the heatpump. Sometimes it disables it instead. In these situations I found that writing a 2 would enable it, but then again that disables the heatpump at other times. Quite mysterious.

In the end I settled at writing a value of 255. This somehow seems to always work.

https://github.com/mvdklip/Domoticz-Hewalex/commit/ff7b02f696b2ecd15025f325adfc70cbb166c881

**Comment by mvdklip** [comment]
I'm also thinking that I maybe should separate the hewalex_geco Python library and put it in PyPI.

**Comment by Chibald** [comment]
Ah, thanks for pointing that out! As a work around you could also settle on
changing the TapwaterTemp to a low value. It will also disable the
heatpump in a I guess.

In my Mqtt code this the command iI use:
Heatpump/Command/TapWaterTemp

Right now I use it to set a slightly higher value when running legionella
protection. When it reaches this value (54c) I also enable the electrical
heater to get the boiler to 60 degrees and hold it there for at least 20
minutes.

My idea was to set it to a much lower value in the summer. For example when
someone takes a bath in the evening and it will  be sunny the next day, the
heatpump can take a rest.
But right now it is not sunny enough ;)

About  hewalex_geco: I made a few small changes to your python
hewalex_geco. I moved the description to a field in the array. This way I
am able to make a table for the readme.md with description of all
registers.
I think It's a nice feature to also have the description there, instead of
comments.

By the way: do you know if it is possible to write the current date and
time on the units?


Op vr 12 nov. 2021 om 10:43 schreef Matthijs van der Klip <
***@***.***>:

**Comment by mvdklip** [comment]
Sorry for responding so late. Have been busy.

It's actually a quite good idea to start tuning the tap water temp instead of enabling/disabling the heatpump. Thanks for that.

The Geco Proto.docx document has some notes about changing the date and time on a PCWU:

"In this mode, you can also change the pump configuration, which is a significant advantage. First of all, you must first find what you want to change, I partially analyzed the registers and the deciphered information is in the description below. Not all parameters I was able to find the possibility of changing the time. It seems that only registers above 255 are modifiable, although it is possible to send a record of the time change to 8 registers at address 120, and the answer is correct, but the time does not change. It is possible that there is another time change command, or some larger register (e.g. above 1000)."

I have documented register 120 as a status register because I also noticed that registers < 0x100 cannot be written too. This means that there could be a yet unknown config register which allows the date and time to be set but does not return the current values. As you can see there are still a lot of gaps in the config registers as they were reverse engineered largely by looking at whether they return meaningful values. The problem is that you probably want to start experimenting with writing to random config registers in the hope that it will change the date and time, right?

Another possibility might be to eavesdrop on the communication between the controller and PCWU and then change the date and time on the controller to find out what message it sends to the PCWU.

**Pull request closed without merging**
